// Default site content. Everything here is editable from /admin; the database copy (if any) is merged over it.
// Copy marked "verbatim" is client-supplied: keep the wording when editing defaults.

const legalName = 'Waterloo Institute of Management Solutions'
const email = 'waterlooinstitute.ms@gmail.com'

export const defaultContent = {
  settings: {
    name: 'WIMs',
    legalName,
    email,
    nasUrl: 'https://nas.com/wims',
    nasLabel: 'nas.com/wims',
    socialHandle: '@chiefsaqifwims',
    youtubeUrl: 'https://youtube.com/@chiefsaqif?si=YcI0_g7gDAh3ZjxT',
    youtubeLabel: 'youtube.com/@chiefsaqif',
    description: 'The next generation of AI-powered education, business tools, and opportunities — all in one platform',
  },
  navigation: {
    home: 'Home',
    services: 'Services',
    testimonials: 'Testimonials',
    faq: 'FAQ',
    contact: 'Contact',
    nasLink: 'NAS',
    joinCta: 'Join the community',
    contactCta: 'Contact WIMs',
  },
  seo: {
    keywords: ['WIMs', legalName, 'AI education', 'AI community', 'AI lead generation', 'NAS community', 'entrepreneurs', 'small business AI'],
    pages: {
      services: { title: 'AI Lead Generation Services', description: 'WIMs offers AI lead generation services for organizations looking to explore AI-powered business opportunities. Pricing is custom — contact WIMs for pricing.' },
      testimonials: { title: 'Testimonials', description: 'Trusted by professionals from organizations including Marriott International, Leadpoet, Aramark, and Amazon. Watch video stories from the WIMs community.' },
      faq: { title: 'FAQ', description: 'Answers about WIMs, who the community is for, what members receive, AI lead generation services, pricing, the WIMs AI Club, and the NAS community.' },
      contact: { title: 'Contact', description: `Contact WIMs about the community or AI lead generation services. Email ${email} or join the community at nas.com/wims.` },
      privacy: { title: 'Privacy Policy', description: 'How WIMs collects, uses, and protects information shared through this website.' },
      terms: { title: 'Terms & Conditions', description: 'The terms that apply when you use the WIMs website.' },
    },
  },
  home: {
    // verbatim (client-approved wording)
    heroLines: ['Learn. Build.', 'Grow with AI.'],
    heroDeck: 'The next generation of AI-powered education, business tools, and opportunities — all in one platform',
    heroImage: '/wims-hero.png',
    heroImageAlt: 'A WIMs professional standing in a dark glass studio crossed by lines of golden light',
    heroAltImage: '/images/wimimg.png',
    heroSecondaryCta: 'Discover WIMs',
    heroAside: 'Contact WIMs about AI lead generation services',
    introLabel: 'What WIMs is',
    intro: 'WIMs is an ed tech startup and a private community for professionals and entrepreneurs looking to use AI to grow their income, careers, and businesses.',
    pillars: ['Learn AI.', 'Build Skills.', 'Create Income Streams.'],
    membersLabel: 'Our members',
    members: 'Our members include professionals who work at, or have gone on to join, leading companies such as Nasdaq, Amazon, Marriott International, Leadpoet, and Aramark.',
    companies: ['Nasdaq', 'Amazon', 'Marriott International', 'Leadpoet', 'Aramark'],
    nasTitle: 'The WIMs community lives on NAS.',
    benefits: 'Members also receive access to discounts, credits, and benefits for state-of-the-art AI tools and models through WIM’s partnerships with leading technology companies.',
    guidance: 'In addition, they gain practical strategies, peer support, and ongoing guidance to confidently apply AI across areas such as marketing and sales.',
    nasCta: 'Join the community on NAS',
    portalCta: 'Open the WIMs community',
    serviceLabel: 'Services',
    servicePricingLine: 'Pricing is custom. Contact WIMs for pricing.',
    serviceCta: 'Contact WIMs for pricing',
    serviceLink: 'Explore the service',
    trustLabel: 'Testimonials',
    trusted: 'Trusted by professionals from organizations including Marriott International, Leadpoet, Aramark, and Amazon',
    trustCta: 'View member stories',
    closingTitle: 'Learn. Build. Grow with AI.',
  },
  club: {
    label: 'Member advantage',
    offer: 'Customers who join the WIMs AI Club receive a discount on the AI lead generation services.',
    cta: 'Join the WIMs AI Club',
    cardName: 'WIMs AI Club',
    cardLine: 'Exclusive member benefits',
    cardPerk: 'Discount on AI lead generation services',
    benefitsTitle: 'What WIMs AI Club members get',
    benefits: ['AI skills hub', 'AI prompt library', 'AI templates', 'Real-world projects', 'Community networking', 'Live workshops', 'Challenges', 'Members-only resources', 'AI monthly updates'],
  },
  services: {
    name: 'AI lead generation services',
    heroDeck: 'WIMs offers AI lead generation services for organizations looking to explore AI-powered business opportunities.',
    heroImage: '/images/wims-studio.jpg',
    cta: 'Contact WIMs for pricing',
    pricingTitle: 'Pricing is custom.',
    pricingText: 'Every organization starts from a different place, so WIMs does not publish a fixed price. Contact WIMs to discuss your needs and receive pricing for your organization.',
    stepsLabel: 'How it works',
    steps: [
      { title: 'Tell us about your organization', text: 'Send an inquiry with a short description of your business and what you want to achieve.' },
      { title: 'Discuss your needs with WIMs', text: 'WIMs reviews your inquiry and talks through how AI lead generation could fit your organization.' },
      { title: 'Receive custom pricing', text: 'Pricing is custom, so you receive a quote for your organization rather than a fixed package.' },
    ],
    closingTitle: 'Make your next move more intelligent.',
    closingSecondaryCta: 'Read the FAQ',
  },
  testimonialsPage: {
    heroTitle: 'Member stories, in their own words.',
    heroDeck: 'Trusted by professionals from organizations including Marriott International, Leadpoet, Aramark, and Amazon',
    heroImage: '/images/wimimg.png',
    logosLabel: 'Trusted by employees from',
    closingTitle: 'Your story starts in the community.',
  },
  logos: [
    { name: 'Nasdaq', image: '/images/logo-nasdaq.png' },
    { name: 'Amazon', image: '/images/logo-amazon.png' },
    { name: 'Marriott International', image: '/images/logo-marriott.png' },
    { name: 'Leadpoet', image: '/images/logo-leadpoet.png' },
    { name: 'Aramark', image: '/images/logo-aramark.png' },
  ],
  faq: {
    heroTitle: 'Questions worth asking.',
    heroDeck: 'Straight answers about the community, the service, and how to get started.',
    heroImage: '/images/wims-stair.jpg',
    asideText: 'Can’t find your answer?',
    items: [
      { q: 'What is WIMs?', a: 'WIMs is an ed tech startup and a private community for professionals and entrepreneurs looking to use AI to grow their income, careers, and businesses.' },
      { q: 'Who is the community for?', a: 'WIMs is for entrepreneurs, university students, and small business owners who want to learn AI, build skills, and create income streams.' },
      { q: 'What do members receive?', a: 'Members receive access to discounts, credits, and benefits for state-of-the-art AI tools and models through WIM’s partnerships with leading technology companies. In addition, they gain practical strategies, peer support, and ongoing guidance to confidently apply AI across areas such as marketing and sales.' },
      { q: 'What do WIMs AI Club members get?', a: 'WIMs AI Club members get an AI skills hub, an AI prompt library, AI templates, real-world projects, community networking, live workshops, challenges, members-only resources, and AI monthly updates. They also receive a discount on the AI lead generation services.' },
      { q: 'What are the AI lead generation services?', a: 'WIMs offers AI lead generation services for organizations looking to explore AI-powered business opportunities. Contact WIMs to discuss your needs.' },
      { q: 'How much do the AI lead generation services cost?', a: 'Pricing is custom. Contact WIMs for pricing.' },
      { q: 'Is there a discount for WIMs AI Club members?', a: 'Yes. Customers who join the WIMs AI Club receive a discount on the AI lead generation services.' },
      { q: 'How do I access the WIMs community on NAS?', a: 'Visit the WIMs community on NAS at https://nas.com/wims.' },
    ],
  },
  contact: {
    heroTitle: 'Let’s talk about what you’re building.',
    heroDeck: 'Whether you’re exploring the WIMs community or AI lead generation services, send an inquiry or reach out directly.',
    heroImage: '/images/wims-network.jpg',
    emailLabel: 'Email',
    communityLabel: 'Community',
    socialLabel: 'Social',
    interestLabel: 'I’m interested in',
    interests: ['WIMs community', 'AI lead generation services', 'Both'],
    nameField: 'Name',
    emailField: 'Email',
    organizationField: 'Organization',
    messageField: 'What are you building?',
    submitLabel: 'Send inquiry',
    successTitle: 'Inquiry sent.',
    successText: 'Thank you. The WIMs team will reply to the email address you provided.',
  },
  footer: {
    exploreLabel: 'Explore',
    communityLabel: 'Community',
    contactLabel: 'Contact',
    inquiryLink: 'Send an inquiry',
    rights: 'All rights reserved.',
  },
  notFound: {
    code: '404',
    title: 'This page isn’t part of the network.',
    text: 'The link may be broken, or the page may have moved. Everything else is one step away.',
    homeCta: 'Return to WIMs',
  },
  legal: {
    privacy: {
      title: 'Privacy Policy',
      deck: 'How WIMs handles the information you share through this website.',
      updated: 'October 5, 2026',
      sections: [
        { title: 'Overview', body: `This Privacy Policy explains how WIMs (${legalName}, “WIMs”, “we”, “us”) handles information when you visit this website or contact us through it. By using this website, you agree to the practices described here.` },
        { title: 'Information we collect', body: '**Information you give us.** When you send an inquiry, we receive and store the details you choose to share, such as your name, email address, organization, area of interest, and message.\n\n**Information collected automatically.** We use privacy-focused website analytics to understand how the site is used, such as which pages are visited. This information is aggregated and is not used to identify you personally.' },
        { title: 'How we use information', body: '- To respond to your inquiry about the WIMs community or AI lead generation services.\n- To provide information you request, including pricing for services.\n- To understand and improve how this website works.\n- To meet legal obligations where they apply.' },
        { title: 'How information is shared', body: 'We do not sell your personal information. We may share information with service providers who help us operate this website and respond to inquiries, only as needed for those purposes, or where required by law.' },
        { title: 'Third-party platforms', body: 'This website links to services operated by others, including the WIMs community on NAS (https://nas.com/wims) and YouTube. When you use those services, their own terms and privacy policies apply. We are not responsible for their practices.' },
        { title: 'Retention and security', body: 'We keep inquiry information only for as long as it is needed for the purposes described in this policy, and we take reasonable measures to protect it. No method of transmission or storage is completely secure.' },
        { title: 'Your choices', body: `You can ask us to access, correct, or delete the personal information you have shared with us by emailing ${email}. You can also choose not to send an inquiry and still browse this website.` },
        { title: 'Children', body: 'This website is intended for professionals, entrepreneurs, students, and business owners. It is not directed at children, and we do not knowingly collect information from children.' },
        { title: 'Changes to this policy', body: 'We may update this Privacy Policy from time to time. The “last updated” date at the top of this page shows when it was last changed.' },
        { title: 'Contact', body: `Questions about this Privacy Policy can be sent to ${email}.` },
      ],
    },
    terms: {
      title: 'Terms & Conditions',
      deck: 'The terms that apply when you use the WIMs website.',
      updated: 'October 5, 2026',
      sections: [
        { title: 'Acceptance of these terms', body: `These Terms & Conditions apply to your use of this website, operated by WIMs (${legalName}, “WIMs”, “we”, “us”). By using the website, you agree to these terms. If you do not agree, please do not use the website.` },
        { title: 'Use of the website', body: 'You may use this website for lawful purposes to learn about WIMs, the WIMs community, and WIMs services. You agree not to:\n\n- use the website in a way that breaks any applicable law;\n- attempt to interfere with the website’s security or operation;\n- submit false, misleading, or harmful information through the inquiry form.' },
        { title: 'The WIMs community on NAS', body: 'The WIMs community is hosted on NAS at https://nas.com/wims. Membership and participation in the community are subject to the terms and policies of that platform in addition to any community guidelines WIMs provides there.' },
        { title: 'AI lead generation services', body: 'Information about AI lead generation services on this website is general and does not form an offer. Pricing is custom and is provided on request. Any engagement is governed by the specific terms agreed between you and WIMs at that time. Customers who join the WIMs AI Club receive a discount on the AI lead generation services, as confirmed in those agreed terms.' },
        { title: 'Intellectual property', body: 'The content of this website, including text, design, graphics, and the WIMs name, belongs to WIMs or its licensors. You may not copy, reproduce, or reuse it for commercial purposes without our written permission.' },
        { title: 'External links', body: 'This website links to third-party websites and platforms, such as NAS and YouTube. We do not control those websites and are not responsible for their content, availability, or practices.' },
        { title: 'No guarantees', body: 'This website and its content are provided “as is” for general information. We work to keep it accurate and available, but we do not guarantee that it is complete, error-free, or uninterrupted, and we do not promise any particular business, career, or income outcome.' },
        { title: 'Limitation of liability', body: 'To the extent permitted by applicable law, WIMs is not liable for any indirect or consequential loss arising from your use of this website or reliance on its content.' },
        { title: 'Changes to these terms', body: 'We may update these Terms & Conditions from time to time. The “last updated” date at the top of this page shows when they were last changed. Continued use of the website means you accept the updated terms.' },
        { title: 'Contact', body: `Questions about these Terms & Conditions can be sent to ${email}.` },
      ],
    },
  },
}

export type Content = typeof defaultContent
